@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":GreyBookParser" as GreyBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> GreyBookParser : parseCommand(undo)
activate GreyBookParser

create UndoCommand
GreyBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> GreyBookParser
deactivate UndoCommand

GreyBookParser --> LogicManager : u
deactivate GreyBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoGreyBook()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
