@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":GreyBookParser" as GreyBookParser LOGIC_COLOR
participant ":ViewCommandParser" as ViewCommandParser LOGIC_COLOR
participant "v:ViewCommand" as ViewCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("view 1")
activate LogicManager

LogicManager -> GreyBookParser : parseCommand("view 1")
activate GreyBookParser

create ViewCommandParser
GreyBookParser -> ViewCommandParser
activate ViewCommandParser

ViewCommandParser --> GreyBookParser
deactivate ViewCommandParser

GreyBookParser -> ViewCommandParser : parse("1")
activate ViewCommandParser

create ViewCommand
ViewCommandParser -> ViewCommand
activate ViewCommand

ViewCommand --> ViewCommandParser :
deactivate ViewCommand

ViewCommandParser --> GreyBookParser : v
deactivate ViewCommandParser

ViewCommandParser -[hidden]-> GreyBookParser
destroy ViewCommandParser

GreyBookParser --> LogicManager : v
deactivate GreyBookParser

LogicManager -> ViewCommand : execute(m)
activate ViewCommand

ViewCommand -> Model : updateFilteredPersonList(p -> p == personToView)
activate Model
Model --> ViewCommand
deactivate Model

create CommandResult
ViewCommand -> CommandResult : "Listed person"
activate CommandResult
CommandResult --> ViewCommand
deactivate CommandResult

ViewCommand --> LogicManager : r
deactivate ViewCommand

[<-- LogicManager
deactivate LogicManager
@enduml
